--- #YAML:1.0
name: Algorithm-ScheduledPath
version: 0.41_02
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Find scheduled paths in a directed graph
license: perl
requires:
  Carp: 0
  Carp::Assert: 0
  Class::Meta: 0.44
  Clone: 0.15
  Data::Types: 0.03
  Scalar::Util: 1.1
  overload: 0
  perl: 5.6.1
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
provides:
  Algorithm::ScheduledPath:
    file: lib/Algorithm/ScheduledPath.pm
    version: 0.41_02
  Algorithm::ScheduledPath::Edge:
    file: lib/Algorithm/ScheduledPath/Edge.pm
    version: 0.41_02
  Algorithm::ScheduledPath::Path:
    file: lib/Algorithm/ScheduledPath/Path.pm
    version: 0.41_01
  Algorithm::ScheduledPath::Types:
    file: lib/Algorithm/ScheduledPath/Edge.pm
    version: 0.41_02
generated_by: Module::Build version 0.2602
